### ISSUE TITLE
DuckDuckGo Bang Integration

### ISSUE THREAD

**Issue by Propheis** [ChrisCooper/QcumberD#103]
Hey!

I thought it'd be a good idea to let you know I've added a Bang integration to the [DuckDuckGo](https://duckduckgo.com) search engine.

People can now use `!qcumber <search query>` to directly search qcumber from duckduckgo. 

Check [this page](https://duckduckgo.com/bang?q=qcumber).

**Comment by ChrisCooper** [comment]
Awesome! Thanks Kevin!
